version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: DB_NAME
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django: 
    build: ./backend
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env                
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres

  react:
    build: ./frontend
    container_name: react
    command: npm start
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  postgres_data: