version: '3.7'

services:
  db:
    image: postgres:latest
    env_file:
      - ./backend/.env 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  create_table:
    build: ./backend
    env_file:
      - ./backend/.env
    command: python manage.py createcachetable
    depends_on:
      db:
        condition: service_healthy

  migrate:
    build: ./backend
    container_name: migrate
    env_file:
      - ./backend/.env
    command: python3 manage.py migrate
    depends_on:
      - create_table

  django: 
    build: ./backend
    container_name: django
    env_file:
      - ./backend/.env 
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"             
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - migrate

  react:
    build: ./frontend
    container_name: react
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
