version: 2.1

jobs:
  build_frontend:
    docker:
      - image: cimg/node:21.4.0
    working_directory: ~/Ecommerce/frontend
    steps:
      - checkout:
          path: ~/Ecommerce
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test

  build_backend:
    docker:
      - image: cimg/python:3.10.14
      - image: cimg/postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dbname
          SECRET_KEY: u^a-fhy%&baknzi47gbw4qcj99_ha#)pawj%n7um%mq%w+o(yf
    working_directory: ~/Ecommerce/backend
    steps:
      - checkout:
          path: ~/Ecommerce
      - run:
          name: Set Environment Variable
          command: echo "export MY_SECRET_KEY=your_secret_key_here" >> "$BASH_ENV"
          environment:
            MY_SECRET_KEY: your_secret_key_here
      - run:
          name: Wait for DB
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for DB && exit 1
      - run:
          name: Install Python dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Apply Database Migrations
          command: |
            python manage.py migrate
      - run:
          name: Run Python tests
          command: |
            python manage.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_frontend
      - build_backend
