version: 2.1
orbs:
  node: circleci/node@5.0.2

workflows:
  sample:
    jobs:
      - build:
          working_directory: ~/Ecommerce/frontend
      - node/test:
          version: '16.16.0'
          test-results-for: jest
          pkg-manager: npm
