# Generated by Django 5.0.3 on 2024-03-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_product_added_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
