# Generated by Django 5.0.3 on 2024-03-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_cart_items_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='order.product'),
        ),
    ]
