# Generated by Django 5.0.3 on 2024-03-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_customer_favorites'),
    ]

    operations = [
    ]
