# Generated by Django 5.0.3 on 2024-04-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_product_discount_percentage_product_is_discounted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(related_name='customers', to='order.product'),
        ),
    ]
