# Generated by Django 5.0.3 on 2024-04-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('order', '0012_remove_cart_total_remove_customer_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='user permissions'),
        ),
    ]
