# Generated by Django 5.0.4 on 2024-05-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('suits', 'Suits'), ('shirt', 'Shirts'), ('neckwear', 'Neckwear & Accessories'), ('shoes', 'Shoes')], max_length=100),
        ),
    ]
