# Generated by Django 5.0.6 on 2024-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
