# Generated by Django 5.0.6 on 2024-05-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_remove_product_is_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
