# Generated by Django 5.0.6 on 2024-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_remove_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
