# Generated by Django 5.0.6 on 2024-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
    ]
