# Generated by Django 5.0.6 on 2024-07-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_alter_customer_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='verification_code',
        ),
    ]
